version: "3"
services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/usr/app/src
      - ./frontend/public:/usr/app/public
    depends_on:
      - backend
    environment:
      - REACT_APP_SERVER=/backend
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./backend:/usr/app/src
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017
      - CLIENT=http://localhost:4000
    command: npm start

  db:
    image: mongo:5.0.5
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

volumes:
  mongo-data:
    driver: local